spring.application.name=ms-notification
server.port=8083

spring.datasource.url=${NOTIF_DB_URL}
spring.datasource.username=${NOTIF_DB_USER}
spring.datasource.password=${NOTIF_DB_PASS}

spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.rabbitmq.host=${RABBITMQ_HOST}
spring.rabbitmq.port=${RABBITMQ_PORT}

management.tracing.sampling.probability=1.0
management.zipkin.tracing.endpoint=${ZIPKIN_URL}

logging.file.name=logs/${spring.application.name}.log
logging.logback.rollingpolicy.file-name-pattern=logs/${spring.application.name}-%d{yyyy-MM-dd}.%i.log
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=7
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} [traceId=%X{traceId}, spanId=%X{spanId}] - %msg%n

spring.rabbitmq.template.observation-enabled=true
spring.rabbitmq.listener.simple.observation-enabled=true

resend.api-key=${RESEND_API_KEY:${RESEND_APY_KEY:}}
