spring.application.name=ms-notification
server.port=8083
spring.datasource.url=jdbc:postgresql://localhost:5434/db_notification
spring.datasource.username=${NOTIF_DB_USER}
spring.datasource.password=${NOTIF_DB_PASS}
spring.jpa.hibernate.ddl-auto=update
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672