services:
  zipkin:
    image: openzipkin/zipkin:latest
    ports:
      - "9411:9411"
      
  rabbitmq-server:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq

  postgres-promotion:
    image: postgres:16
    environment:
      POSTGRES_USER: ${PROMO_DB_USER}
      POSTGRES_PASSWORD: ${PROMO_DB_PASS}
      POSTGRES_DB: ${PROMO_DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata-promotion:/var/lib/postgresql/data

  postgres-auth:
    image: postgres:16
    environment:
      POSTGRES_USER: ${AUTH_DB_USER}
      POSTGRES_PASSWORD: ${AUTH_DB_PASS}
      POSTGRES_DB: ${AUTH_DB_NAME}
    ports:
      - "5433:5432"
    volumes:
      - pgdata-auth:/var/lib/postgresql/data

  postgres-notification:
    image: postgres:16
    environment:
      POSTGRES_USER: ${NOTIF_DB_USER}
      POSTGRES_PASSWORD: ${NOTIF_DB_PASS}
      POSTGRES_DB: ${NOTIF_DB_NAME}
    ports:
      - "5434:5432"
    volumes:
      - pgdata-notification:/var/lib/postgresql/data

volumes:
  rabbitmq-data:
  pgdata-promotion:
  pgdata-auth:
  pgdata-notification: