spring.application.name=ms-ranking
server.port=8082
spring.datasource.url=jdbc:postgresql://localhost:5433/db_ranking
spring.datasource.username=${RANKING_DB_USER}
spring.datasource.password=${RANKING_DB_PASS}
spring.jpa.hibernate.ddl-auto=update
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672