spring.application.name=ms-gateway
server.port=8080

auth.public-key=${AUTH_PUBLIC_KEY:}
auth.service.url=${AUTH_SERVICE_URL:http://localhost:8082}
promotion.service.url=${PROMOTION_SERVICE_URL:http://localhost:8081}

spring.rabbitmq.host=${RABBITMQ_HOST}
spring.rabbitmq.port=${RABBITMQ_PORT}

management.tracing.sampling.probability=1.0
management.zipkin.tracing.endpoint=${ZIPKIN_URL}

logging.file.name=logs/${spring.application.name}.log
logging.logback.rollingpolicy.file-name-pattern=logs/${spring.application.name}-%d{yyyy-MM-dd}.%i.log
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=7
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} [traceId=%X{traceId}, spanId=%X{spanId}] - %msg%n

spring.rabbitmq.template.observation-enabled=true
spring.rabbitmq.listener.simple.observation-enabled=true