spring.application.name=ms-promotion
server.port=8081
spring.datasource.url=jdbc:postgresql://localhost:5432/db_promotion
spring.datasource.username=${PROMO_DB_USER}
spring.datasource.password=${PROMO_DB_PASS}
spring.jpa.hibernate.ddl-auto=update
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672